title: "Blog of Carlos Sanchez"
description: "Sharing my learnings."
github_username: carlossanlop
bluesky_username: chayotejarocho.space
mastodon_username: foo_fighter
linkedin_username: carlossanlop

markdown: kramdown
markdown_ext: "markdown,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 2
paginate_path: '/:num/'

sass:
    style: :compressed
    sass_dir: assets/css/
